### PR TITLE
feat: Add sonar workflow

### PR DESCRIPTION
**Pull request by xC0dex**
This PR introduces the initial version of the SonarCloud workflow. https://github.com/MudBlazor/MudBlazor/issues/9236

- Analyzes `MudBlazor`, `MudBlazor.SourceGenerator`, and `MudBlazor.Analyzers` projects.
- Requires secrets from the calling workflow.
- Doesn't depend on any other workflow.

### Not included
- This PR does not include any code coverage-related features.

The calling workflow currently looks like this:
```yml
name: sonar

on:
  workflow_dispatch:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    uses: MudBlazor/Workflows/.github/workflows/template-sonar.yml@main
    secrets: inherit
```

### CODE REVIEW

**Comment by mikes-gh** [comment]
I thought we were replacing codecov to have only one comment in the PR?

**Comment by xC0dex** [comment]
> I thought we were replacing codecov to have only one comment in the PR?

I proposed another idea (https://github.com/MudBlazor/MudBlazor/issues/9236#issuecomment-2211718970) to start without PR decoration initially. So we can configure SonarCloud to our needs and gain some experience of working with it.

**Comment by mikes-gh** [comment]
> > I thought we were replacing codecov to have only one comment in the PR?
> 
> I proposed another idea ([MudBlazor/MudBlazor#9236 (comment)](https://github.com/MudBlazor/MudBlazor/issues/9236#issuecomment-2211718970)) to start without PR decoration initially. So we can configure SonarCloud to our needs and gain some experience of working with it.

Sorry missed it.
In that case I see no reason not to merge.

**Comment by mikes-gh** [comment]
You could add codecoverage and leave codecov in place

**Comment by xC0dex** [comment]
> You could add codecoverage and leave codecov in place

It would require some adjustments for the `dotnet test` command. For instance, I used `/p:CoverletOutputFormat=opencover` instead of `/p:CoverletOutputFormat=cobertura` and I removed `/p:Include='[MudBlazor]*'`. I think it would also work with `cobertura` format, but I never worked with this before.  I don't know what the benefit is to set `/consoleloggerparameters:NoSummary` so I removed this as well.

**Review by ScarletKuro — APPROVED** [review]

**Comment by henon** [comment]
@mikes-gh please merge if you are satisfied

**Comment by henon** [comment]
@mikes-gh probably on vacation?

**Comment by xC0dex** [comment]
Please let me know if there's anything I need to do to get this PR ready to be merged.
I intentionally chose the approach without the PR decoration so that we can get some experience with SonarCloud.

**Comment by henon** [comment]
Basically the worry was that it might strain server resources. We'll try and evaluate.

**Comment by xC0dex** [comment]
> Basically the worry was that it might strain server resources. We'll try and evaluate.

The current execution time is about ~ 2:50 minutes, which should be ok IMO. The project is large, that's why it takes some time. However, only `MudBlazor`, `MudBlazor.SourceGenerator`, and `MudBlazor.Analyzers` will be analyzed currently.

**Comment by mikes-gh** [comment]
> > Basically the worry was that it might strain server resources. We'll try and evaluate.
> 
> The current execution time is about ~ 2:50 minutes, which should be ok IMO. The project is large, that's why it takes some time. However, only `MudBlazor`, `MudBlazor.SourceGenerator`, and `MudBlazor.Analyzers` will be analyzed currently.

Thats fine I thought it was a lot longer.  It runs concurrently and we don't pay for resources so there is no delay in getting all checks passed since other checks take longer

**Comment by xC0dex** [comment]
> It runs concurrently

If we want a coverage report, it would depend on the test job. Concurrency would no longer be possible then. But I would say it's fine for now. Once we reviewed existing rules and SonarCloud findings, we can enable PR decoration and the support for the Coverage Report.

**Pull request merged**
